{
 "title": "CipherStash Proxy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Into and data access events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CipherStash Proxy",
   "type": "text",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 1 },
   "options": {
    "content": "## Log Collection Process\n1. **Log Entries**: Data access events are logged and collected by Promtail.\n2. **Loki Storage**: These logs are then sent to Loki, where they are stored and can be queried.\n3. **Log Details**: Each log entry can be selected to view detailed information about the data access event.\n\n## Streaming Logs to CipherStash Cloud\n\n### Benefits of CipherStash Audit\n- **Enhanced Filtering**: Easily filter logs to find relevant data access events.\n- **Advanced Sorting**: Sort logs based on various criteria for better analysis.\n- **Anomaly Detection**: Automatically detect and flag unusual data access patterns.\n\n### Configuration Steps\n1. **Generate an API Key**: \n   - [Create a CipherStash account](https://cipherstash.com/signup).\n   - Navigate to the API section and generate a new API key.\n   \n2. **Update Proxy Configuration**:\n   - Locate your proxy configuration file.\n   - Add the generated API key to the configuration file.\n   - Ensure the proxy is set to forward logs to CipherStash Cloud.\n\n3. **Immediate Data Collection**:\n   - Once the proxy configuration is updated, logs will be streamed to CipherStash Cloud immediately.\n   - You can now utilize CipherStash Cloud’s tools for filtering, sorting, and anomaly detection."
   }
  },
  {
   "title": "Data access events",
   "type": "logs",
   "gridPos": { "h": 17, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"proxylogs\"} |= `DataAccessLog` | pattern `<_> <_> <_> { id: <id>, workspace_id: \"<workspaceId>\", statement_id: <statementId>, rows_accessed: <rowsAccessed>, columns_accessed: <columnsAccessed>, created_at: <timestamp> <_>>`\n"
    }
   ]
  },
  { "title": "CipherStash Proxy metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total query count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(pgcat_servers_query_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Pool Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgcat_databases_pool_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database current connections ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgcat_databases_current_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average query time (nanoseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(pgcat_stats_avg_query_time[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error count ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pgcat_servers_error_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}