## Sign up for an account to create an access key: https://dashboard.cipherstash.com

# workspace_id = "..."
# client_access_key = "..."

prometheus_metrics = true

# [audit]
# subscriber = "cipherstash"

[database]
name = "postgres"
username = "postgres"
password = "password"

# postrgres host & port
# host = "db"
# port = 5432

# toxiproxy host & port
# enable this to direct traffic through toxiproxy
host = "toxiproxy"
port = 5433

[audit]
subscriber = "cipherstash"
