## Sign up for an account to create an access key: https://dashboard.cipherstash.com

# workspace_id = "..."
# client_access_key = "..."

# [audit]
# subscriber = "cipherstash"

prometheus_metrics = true

[database]
name = "postgres"
port = 5432
host = "db"
username = "postgres"
password = "password"
