apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
    isDefault: true
    uid: loki
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    version: 1
    editable: false
    isDefault: false
    uid: prometheus

dashboards:
  default:
    - folder: ''
      title: 'CipherStash'
      id: 1
      uid: cipherstash
      url: /var/lib/grafana/dashboards/cipherstash.json