server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
          - 
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
    pipeline_stages:
      - match:
          selector: '{job="flog_scrape"}'
          stages:
            - regex:
                expression: '.*DataAccessLog (?P<json_log>\{.*\})'
            - json:
                source: json_log
                expressions:
                  id: id
                  workspace_id: workspace_id
                  statement_id: statement_id
                  rows_accessed: rows_accessed
                  columns_accessed: columns_accessed
                  created_at: created_at
            - output:
                source: json_log
